package vistas;
import controladores.ControladorTabla;
import controladores.ControladorVista;
import javax.swing.JOptionPane;
import logica.Idioma;
import logica.Palabra;
import logica.Termino;
import logica.Traduccion;
import tcpoo.Cliente;

/**
 * FECHA ==> 2019-05-26.
 * Ventana para agregar los datos de un cliente a una venta.
 * @author Luis Alejandro Gómez C.
 * @version 1.0 .
 */
public class EditarTraduccion extends javax.swing.JDialog 
{
    private Traduccion nuevaTraduccion;
    private String traduccion;
    private ControladorTabla controladorTabla;
    private ControladorVista controlVista;
    private Cliente cliente;
    //private Sistema sistema;

    /**
     * Creates new form IngresarCliente
     */
    public EditarTraduccion(java.awt.Frame parent, boolean modal,String traduccion,
                                                                Cliente cliente) 
    {
        //Le llega en el constructo un Termino termino.
        super(parent, modal);
        initComponents();
        this.cliente = cliente;
        this.controlVista = new ControladorVista();
        this.controladorTabla = new ControladorTabla();
        this.setLocationRelativeTo(parent);
        this.traduccion = traduccion;
        //this.sistema = sistema;
        this.inicializarInfo();
                
    }
    
    public void inicializarInfo()
    {
        String respuesta = this.cliente.hablar("listar,idiomas,cliente");
        this.controlVista.llenarCombo(comboIdiomaInicio, respuesta);
        this.controlVista.llenarCombo(comboIdiomaFin, respuesta);

        Traduccion traduc = this.controladorTabla.construirTraduccion(traduccion);
        
        Termino ter1 = traduc.getTermino1();
        Termino ter2 = traduc.getTermino2();

        this.comboIdiomaInicio.setSelectedItem(ter1.getIdioma().getIso() + ":" 
                                                + ter1.getIdioma().getNombre());
        this.comboIdiomaFin.setSelectedItem(ter2.getIdioma().getIso() + ":" 
                                                + ter2.getIdioma().getNombre());
        
        this.txtPalabraInicio.setText(ter1.getPalabra().getTermino());    
        this.txtPalabraFin.setText(ter2.getPalabra().getTermino());  
    }

    public Traduccion getNuevaTraduccion() {
        return nuevaTraduccion;
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        panelEncabezado = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        txtEncabezado = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPalabraInicio = new javax.swing.JTextField();
        comboIdiomaInicio = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtPalabraFin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboIdiomaFin = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelEncabezado.setBackground(new java.awt.Color(36, 52, 81));

        txtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoCerrar.png"))); // NOI18N
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
        });

        txtEncabezado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        txtEncabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_editar_termino.png"))); // NOI18N
        txtEncabezado.setText("      Editar Término");

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncabezadoLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(txtEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSalir)
                .addGap(20, 20, 20))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSalir)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(txtEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnAceptar.setBackground(new java.awt.Color(20, 60, 108));
        btnAceptar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(176, 95, 95));
        btnCancelar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Palabra Inicial");

        txtPalabraInicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        comboIdiomaInicio.setBackground(new java.awt.Color(36, 52, 81));
        comboIdiomaInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboIdiomaInicio.setForeground(new java.awt.Color(255, 255, 255));
        comboIdiomaInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "es:español" }));
        comboIdiomaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIdiomaInicioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Idioma Origen");

        txtPalabraFin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Traducción");

        comboIdiomaFin.setBackground(new java.awt.Color(36, 52, 81));
        comboIdiomaFin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboIdiomaFin.setForeground(new java.awt.Color(255, 255, 255));
        comboIdiomaFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "en:ingles" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Idioma Destino");

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPalabraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel3))
                            .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(comboIdiomaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67)
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPalabraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(comboIdiomaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(50, 50, 50)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPalabraFin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPalabraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboIdiomaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboIdiomaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        
        //do {            
            if(txtPalabraInicio.getText().equals("") || txtPalabraFin.getText().equals(""))
                JOptionPane.showMessageDialog(this, "No pueden existir campos vacios");
            else
            {
                //this.cliente=new Cliente();
                String palabraInicio=txtPalabraInicio.getText().trim().toLowerCase();
                String[]arreglo = ((String)comboIdiomaInicio.getSelectedItem()).split(":");
                Palabra palabra1=new Palabra(-1, palabraInicio);
                Idioma idioma1= new Idioma(arreglo[0],arreglo[1]);
                Termino t1 = new Termino(palabra1, idioma1);

                String palabraFin=txtPalabraFin.getText().trim().toLowerCase();
                String[]arreglo2= ((String)comboIdiomaFin.getSelectedItem()).split(":");
                Palabra palabra2=new Palabra(-1, palabraFin);
                Idioma idioma2= new Idioma(arreglo2[0], arreglo2[1]);
                Termino t2 = new Termino(palabra2, idioma2);
                this.nuevaTraduccion = new Traduccion(t1, t2);
                this.dispose();
            }
            
            
        //} while (txtPalabraInicio.getText().equals("") || txtPalabraFin.getText().equals(""));  
        

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked

    }//GEN-LAST:event_btnAceptarMouseClicked

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtSalirMouseClicked

    private void comboIdiomaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIdiomaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboIdiomaInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> comboIdiomaFin;
    private javax.swing.JComboBox<String> comboIdiomaInicio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JLabel txtEncabezado;
    private javax.swing.JTextField txtPalabraFin;
    private javax.swing.JTextField txtPalabraInicio;
    private javax.swing.JLabel txtSalir;
    // End of variables declaration//GEN-END:variables
}
