package vistas;

import controladores.ControladorVista;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import logica.Termino;
import tcpoo.Cliente;

/**
 * FECHA ==> 2019-05-10.
 * Ventana principal del sistema.
 * @author Luis Alejandro Gómez C.
 * @version 1.0.0
 */
public class VentanaInicio extends javax.swing.JFrame 
{
    private Border border;
    //private Sistema sistema;
    private Cliente cliente;
    private ControladorVista controlVista;
    
    public VentanaInicio(Cliente cliente)//Sistema sistema ) 
    {          
        initComponents();
        //this.setVisible(true);
        this.controlVista = new ControladorVista();
        this.cliente = cliente;
        //Para llenar los comboBox.
        //this.cliente.setPeticion("chao");
        String respuesta = this.cliente.hablar("listar,idiomas,cliente");
        this.controlVista.llenarCombo(comboIdiomaOrigen, respuesta);
        this.controlVista.llenarCombo(comboIdiomaDestino, respuesta);

        //this.sistema=sistema;
        this.setLocationRelativeTo(null);
        this.border= BorderFactory.createLineBorder(Color.GRAY , 2);        
    }
    
    public void crearInteractividadBotones(JLabel boton, boolean indicador)
    {
        if(indicador)
        {
            boton.setBorder(this.border);
        }
        else
        {
            boton.setBorder(null);
        }                     
    } 
    public void click()
    {
        this.crearInteractividadBotones(lblAgregarTermino, false);
        this.crearInteractividadBotones(lblEditarTermino, false);
        this.crearInteractividadBotones(lblConsultarTermino, false);
        this.crearInteractividadBotones(lblEliminarTermino, false);
        //this.crearInteractividadBotones(lblAñadirIdioma, false);
    
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNav = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        txtLogo = new javax.swing.JLabel();
        lblAgregarTermino = new javax.swing.JLabel();
        lblEditarTermino = new javax.swing.JLabel();
        lblConsultarTermino = new javax.swing.JLabel();
        lblEliminarTermino = new javax.swing.JLabel();
        txtSalir = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtFrase = new javax.swing.JTextArea();
        comboIdiomaOrigen = new javax.swing.JComboBox<>();
        comboIdiomaDestino = new javax.swing.JComboBox<>();
        btnTraducir = new javax.swing.JButton();
        txtTraduccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelEncab = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        minim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNav.setBackground(new java.awt.Color(36, 52, 81));
        panelNav.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelLogo.setBackground(new java.awt.Color(0, 1, 63));
        panelLogo.setForeground(new java.awt.Color(0, 102, 153));

        txtLogo.setBackground(new java.awt.Color(0, 102, 153));
        txtLogo.setFont(new java.awt.Font("Candara", 1, 28)); // NOI18N
        txtLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconTraductor.png"))); // NOI18N

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addComponent(txtLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblAgregarTermino.setBackground(new java.awt.Color(255, 255, 255));
        lblAgregarTermino.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        lblAgregarTermino.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarTermino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        lblAgregarTermino.setText("Agregar Término");
        lblAgregarTermino.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAgregarTermino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarTerminoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAgregarTerminoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAgregarTerminoMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAgregarTerminoMouseReleased(evt);
            }
        });

        lblEditarTermino.setBackground(new java.awt.Color(255, 255, 255));
        lblEditarTermino.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        lblEditarTermino.setForeground(new java.awt.Color(255, 255, 255));
        lblEditarTermino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoEditar.png"))); // NOI18N
        lblEditarTermino.setText("Editar Término");
        lblEditarTermino.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblEditarTerminoMouseDragged(evt);
            }
        });
        lblEditarTermino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditarTerminoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEditarTerminoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEditarTerminoMouseExited(evt);
            }
        });

        lblConsultarTermino.setBackground(new java.awt.Color(255, 255, 255));
        lblConsultarTermino.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        lblConsultarTermino.setForeground(new java.awt.Color(255, 255, 255));
        lblConsultarTermino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoLupa.png"))); // NOI18N
        lblConsultarTermino.setText("Consultar Término");
        lblConsultarTermino.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblConsultarTerminoMouseDragged(evt);
            }
        });
        lblConsultarTermino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsultarTerminoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConsultarTerminoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblConsultarTerminoMouseExited(evt);
            }
        });

        lblEliminarTermino.setBackground(new java.awt.Color(255, 255, 255));
        lblEliminarTermino.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        lblEliminarTermino.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminarTermino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoBorrar.png"))); // NOI18N
        lblEliminarTermino.setText("Eliminar Término");
        lblEliminarTermino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarTerminoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEliminarTerminoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEliminarTerminoMouseExited(evt);
            }
        });

        txtSalir.setBackground(new java.awt.Color(255, 255, 255));
        txtSalir.setFont(new java.awt.Font("Candara", 1, 20)); // NOI18N
        txtSalir.setForeground(new java.awt.Color(211, 88, 88));
        txtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        txtSalir.setText("       Salir");
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelNavLayout = new javax.swing.GroupLayout(panelNav);
        panelNav.setLayout(panelNavLayout);
        panelNavLayout.setHorizontalGroup(
            panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelNavLayout.createSequentialGroup()
                .addGroup(panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNavLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAgregarTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEditarTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblConsultarTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEliminarTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelNavLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNavLayout.setVerticalGroup(
            panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavLayout.createSequentialGroup()
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblAgregarTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblEditarTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblConsultarTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblEliminarTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(txtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        getContentPane().add(panelNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 660));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new java.awt.CardLayout());

        panelInicio.setBackground(new java.awt.Color(221, 228, 229));
        panelInicio.setPreferredSize(new java.awt.Dimension(880, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Frase:");

        txtFrase.setColumns(20);
        txtFrase.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtFrase.setRows(5);
        txtFrase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFraseKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtFrase);

        comboIdiomaOrigen.setBackground(new java.awt.Color(36, 52, 81));
        comboIdiomaOrigen.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        comboIdiomaOrigen.setForeground(new java.awt.Color(255, 255, 255));
        comboIdiomaOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboIdiomaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIdiomaOrigenActionPerformed(evt);
            }
        });

        comboIdiomaDestino.setBackground(new java.awt.Color(36, 52, 81));
        comboIdiomaDestino.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        comboIdiomaDestino.setForeground(new java.awt.Color(255, 255, 255));
        comboIdiomaDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboIdiomaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIdiomaDestinoActionPerformed(evt);
            }
        });

        btnTraducir.setBackground(new java.awt.Color(61, 131, 154));
        btnTraducir.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnTraducir.setForeground(new java.awt.Color(255, 255, 255));
        btnTraducir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/translate_7235.png"))); // NOI18N
        btnTraducir.setText("Traducir");
        btnTraducir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraducirActionPerformed(evt);
            }
        });

        txtTraduccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Frase Traducida:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 157, 88));
        jLabel3.setText("Idioma Original");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(211, 88, 88));
        jLabel4.setText("Idioma Destino");

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInicioLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboIdiomaOrigen, 0, 198, Short.MAX_VALUE)
                                    .addComponent(comboIdiomaDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(panelInicioLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel4)))
                        .addContainerGap(187, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                        .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTraduccion)
                            .addGroup(panelInicioLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelInicioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnTraducir)))
                        .addGap(228, 228, 228))
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(221, 221, 221))))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addComponent(comboIdiomaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboIdiomaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnTraducir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtTraduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelInicio, "card2");

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 840, 530));

        panelEncab.setBackground(new java.awt.Color(0, 153, 153));
        panelEncab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Traductor");

        jLabel8.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("uam");

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoCerrar.png"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });

        minim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoMinimizar.png"))); // NOI18N
        minim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelEncabLayout = new javax.swing.GroupLayout(panelEncab);
        panelEncab.setLayout(panelEncabLayout);
        panelEncabLayout.setHorizontalGroup(
            panelEncabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabLayout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(183, 183, 183)
                .addComponent(minim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salir)
                .addGap(155, 155, 155))
            .addGroup(panelEncabLayout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEncabLayout.setVerticalGroup(
            panelEncabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelEncabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salir)
                    .addComponent(minim)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelEncab, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 130));

        setBounds(0, 0, 914, 557);
    }// </editor-fold>//GEN-END:initComponents

    private void lblAgregarTerminoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarTerminoMouseReleased
        
    }//GEN-LAST:event_lblAgregarTerminoMouseReleased

    private void lblAgregarTerminoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarTerminoMouseEntered
        //this.logica.crearInteractividadBotones(this.lblAgregarTermino, true);
    }//GEN-LAST:event_lblAgregarTerminoMouseEntered

    private void lblAgregarTerminoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarTerminoMouseExited
        //this.logica.crearInteractividadBotones(this.lblAgregarTermino, false);
    }//GEN-LAST:event_lblAgregarTerminoMouseExited

    private void lblEditarTerminoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarTerminoMouseEntered
        //this.logica.crearInteractividadBotones(this.lblEditarTermino, true);
    }//GEN-LAST:event_lblEditarTerminoMouseEntered

    private void lblEditarTerminoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarTerminoMouseExited
        //this.logica.crearInteractividadBotones(this.lblEditarTermino, false);
    }//GEN-LAST:event_lblEditarTerminoMouseExited

    private void lblConsultarTerminoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultarTerminoMouseEntered
        //this.logica.crearInteractividadBotones(this.lblConsultarTermino, true);
    }//GEN-LAST:event_lblConsultarTerminoMouseEntered

    private void lblConsultarTerminoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultarTerminoMouseExited
        //this.logica.crearInteractividadBotones(this.lblConsultarTermino, false);
    }//GEN-LAST:event_lblConsultarTerminoMouseExited

    private void lblEliminarTerminoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarTerminoMouseEntered
        //this.logica.crearInteractividadBotones(this.lblEliminarTermino, true);
    }//GEN-LAST:event_lblEliminarTerminoMouseEntered

    private void lblEliminarTerminoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarTerminoMouseExited
        //this.logica.crearInteractividadBotones(this.lblEliminarTermino, false);
    }//GEN-LAST:event_lblEliminarTerminoMouseExited

    private void txtSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseEntered
        //this.logica.crearInteractividadBotones(this.txtSalir, true);
    }//GEN-LAST:event_txtSalirMouseEntered

    private void txtSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseExited
        //this.logica.crearInteractividadBotones(this.txtSalir, false);
    }//GEN-LAST:event_txtSalirMouseExited

    private void lblAgregarTerminoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarTerminoMouseClicked
       this.click();
       this.crearInteractividadBotones(lblAgregarTermino, true);
       AgregarTermino agregar = new AgregarTermino(this, true, cliente);//, "Término");
       agregar.setVisible(true);
       Termino t1= agregar.getT1();
       Termino t2=agregar.getT2();
       if(t1 != null && t2 != null)
       {
           String terminos = t1.getPalabra().getId() + "/" + t1.getPalabra().getTermino()
                   + "/" + t1.getIdioma().getIso() + "/" + t1.getIdioma().getNombre() + ":"
                   + t2.getPalabra().getId() + "/" + t2.getPalabra().getTermino()
                   + "/" + t2.getIdioma().getIso() + "/" + t2.getIdioma().getNombre();
           String respuesta = this.cliente.hablar("agregar,traduccion," + terminos);
           
            if(respuesta.equals("si"))
                JOptionPane.showMessageDialog(this, "Se Agregó Correctamente");
            else
                JOptionPane.showMessageDialog(this, "No se pudó agregar");
            
       }   
    }//GEN-LAST:event_lblAgregarTerminoMouseClicked

    private void lblEditarTerminoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarTerminoMouseClicked
       this.click();
       this.crearInteractividadBotones(lblEditarTermino, true);
       
       //this.cliente = new Cliente();
       EditarTermino editar = new EditarTermino(this, true, this.cliente);
       editar.setVisible(true);
       
    }//GEN-LAST:event_lblEditarTerminoMouseClicked

    private void lblConsultarTerminoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultarTerminoMouseClicked
       this.click();
       this.crearInteractividadBotones(lblConsultarTermino, true);       
       
       ConsultarTermino dialogoConsultar= new ConsultarTermino(this, true, this.cliente);
       dialogoConsultar.setVisible(true);
       
    }//GEN-LAST:event_lblConsultarTerminoMouseClicked

    private void lblEliminarTerminoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarTerminoMouseClicked
       this.click();
       this.crearInteractividadBotones(lblEliminarTermino, true);
       EliminarTermino dialogoEliminar = new EliminarTermino(this, true, this.cliente);
       dialogoEliminar.setVisible(true);
        
    }//GEN-LAST:event_lblEliminarTerminoMouseClicked

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtSalirMouseClicked
    
    private void lblEditarTerminoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditarTerminoMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEditarTerminoMouseDragged

    private void lblConsultarTerminoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultarTerminoMouseDragged
        
    }//GEN-LAST:event_lblConsultarTerminoMouseDragged

    private void minimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void comboIdiomaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIdiomaOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboIdiomaOrigenActionPerformed

    private void comboIdiomaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIdiomaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboIdiomaDestinoActionPerformed

    private void btnTraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraducirActionPerformed
        String[] idiOrigen = ((String)this.comboIdiomaOrigen.getSelectedItem()).split(":");
        String[] idiDest = ((String)this.comboIdiomaDestino.getSelectedItem()).split(":");

        String[] palabras = (this.txtFrase.getText().toLowerCase()).split(" ");
        String palabraSeparada = "";
        
        for (int i = 0; i < palabras.length; i++) 
        {
            palabraSeparada += palabras[i] + "-";            
        }
        
        //le envio el idioma origen y destino.
        String isos = idiOrigen[0] + "!" + idiDest[0];
        
        
        String rpta = this.cliente.hablar("traducirFrase," + isos + "," + palabraSeparada);
        this.txtTraduccion.setText(rpta.replace("-", " "));
            
    }//GEN-LAST:event_btnTraducirActionPerformed

    private void txtFraseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFraseKeyTyped
        int lonTexto = this.txtFrase.getText().length();
        //if(lonTexto > )
        
        
    }//GEN-LAST:event_txtFraseKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTraducir;
    private javax.swing.JComboBox<String> comboIdiomaDestino;
    private javax.swing.JComboBox<String> comboIdiomaOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregarTermino;
    private javax.swing.JLabel lblConsultarTermino;
    private javax.swing.JLabel lblEditarTermino;
    private javax.swing.JLabel lblEliminarTermino;
    private javax.swing.JLabel minim;
    private javax.swing.JPanel panelEncab;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelNav;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel salir;
    private javax.swing.JTextArea txtFrase;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JLabel txtSalir;
    private javax.swing.JTextField txtTraduccion;
    // End of variables declaration//GEN-END:variables
}
